osx_image: xcode8.3
language: swift

before_install:
  - ls -al
  - ./install_swiftlint.sh
  - sudo gem install bundler
  - bundle install
  - which swiftlint
  - bundle exec danger
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - set -o pipefail && xcodebuild -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -workspace iOSJenkinsCI.xcworkspace -scheme 'iOSJenkinsCI' -sdk iphonesimulator clean build test | xcpretty -c
